spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 441654377790-eh3kc8479gidse8cgo49fgi54gqnpseh.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8080/login/oauth2/google"
            authorization-grant-type: authorization_code
            scope: email

          naver:
            client-id: hp2FfQsPd8rf9BrH3NIS
            client-secret: sgQTKeLaYO
            redirect-uri: "http://localhost:8080/login/oauth2/naver"
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: naver

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://nid.naver.com/v1/nid/me
            user_name_attribute: response